# Generated by Django 6.0.3 on 2026-04-03 23:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_product_profit_margin_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('155.00'), max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('freight_documentation', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bank_lc_charge', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('inland_transport', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('storage_modjo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('demurrage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('loading_unloading', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('scanning', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('professional_salary', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('custom_duty_percent', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('custom_duty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_additional_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fob_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_share_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('allocated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unit_landed_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='landing.shipment')),
            ],
        ),
    ]
