# Generated by Django 6.0.3 on 2026-04-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='clearing_agent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='miscellaneous_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
