# Generated by Django 6.0.3 on 2026-03-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='expiry_date',
        ),
    ]
