# Generated by Django 6.0.3 on 2026-04-01 13:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VATReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_vat_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_wht_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
