# Generated by Django 6.0.3 on 2026-04-01 12:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale__cost_total_sale__unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='wht_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=5),
        ),
    ]
