# Generated by Django 6.0.3 on 2026-04-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_wht_amount_sale_wht_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='consumed_batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='consumed_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
