# Generated by Django 6.0.3 on 2026-05-06 00:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_shipment_clearing_agent_shipment_miscellaneous_cost"),
        ("sales", "0006_sale_approved_at_sale_approved_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleBatchAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch_number", models.CharField(max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("total_cost", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sale", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="sales.sale")),
                ("shipment_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sale_allocations", to="landing.shipmentitem")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="salebatchallocation",
            constraint=models.UniqueConstraint(fields=("sale", "shipment_item"), name="unique_sale_shipment_item_allocation"),
        ),
    ]
