# Generated by Django 6.0.3 on 2026-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_controlled_product_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
