# Generated by Django 6.0.3 on 2026-03-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_sale_unit_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
