# Generated by Django 6.0.3 on 2026-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_margin_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
